#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ -e "${ZDOTDIR:-$HOME}/.zshenv.secret" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshenv.secret"
fi

# nylas specific config
export VAGRANT_CWD=~/src/nylas/redwood/
export DOCKER_HOST=tcp://192.168.59.103:2376
#export DOCKER_CERT_PATH=$HOME/.docker/machine/machines/default
#export DOCKER_TLS_VERIFY=1
#export DOCKER_MACHINE_NAME=default
