#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ls='ls -Gl'
alias vim='nvim'

export GOPATH='/Users/mik/src/go'
export KEYTIMEOUT=1

# Use vim cli mode
bindkey -v 
bindkey '^P' up-history
bindkey '^N' down-history

# ctrl-r starts searching history backward
bindkey '^r' history-incremental-search-backward

PATH=$PATH:$GOPATH/bin
