#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ls='ls -Gl'
alias vim='nvim'

export GOPATH=$HOME/src/go
export KEYTIMEOUT=1
export HOMEBREW_GITHUB_API_TOKEN='e9d95a2b09cf997d8311b86ad52c21aa45107954'

# Use vim cli mode
bindkey -v 
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word

# ctrl-r starts searching history backward
bindkey '^r' history-incremental-search-backward

PATH=$PATH:$GOPATH/bin
PATH=$PATH:$HOME/src/arcanist/arcanist/bin

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export nvm_dir="$home/.nvm"
[ -s "$nvm_dir/nvm.sh" ] && \. "$nvm_dir/nvm.sh"  # this loads nvm
[ -s "$nvm_dir/bash_completion" ] && \. "$nvm_dir/bash_completion"  # this loads nvm bash_completion

eval "$(rbenv init -)"
eval "$(direnv hook zsh)"
